<?php

/**
 * @file
 * Contains simple_access_log.module.
 */

function simple_access_log__log_request(){
  //do nothing!
  $message = 'simple access log request';
  //request Time
  $access_log = [];

  $access_log['request_time'] = \Drupal::time()->getRequestTime();

  //User or Anon
  $access_log['uid'] = \Drupal::currentUser()->id();

  //Hostname (can we help with the whole forwarded from thing?
  $access_log['remote_host'] = $_SERVER['REMOTE_ADDR'];

  $access_log['host'] = (strlen($_SERVER['SERVER_NAME'])>1?$_SERVER['SERVER_NAME']:$_SERVER['SERVER_ADDR']);

  //Page Title
  $request = \Drupal::request();
  $access_log['title'] = '';
  if ($route = $request->attributes->get(\Symfony\Cmf\Component\Routing\RouteObjectInterface::ROUTE_OBJECT)) {
    $access_log['title'] .= \Drupal::service('title_resolver')->getTitle($request, $route);
  }


  //Path
  $access_log['path'] = $_SERVER['REQUEST_URI'];

  //Referrer
  $access_log['referrer'] = $_REQUEST['HTTP_REFERRER'];

  //User Agent
  $access_log['user_agent'] = $_REQUEST['HTTP_USER_AGENT'];

  // Log to watch dog so we know that this module is being called. Dev testing only.
  dpm($access_log);
  \Drupal::logger('my_module')->debug($message.' '.$access_log['path']);
}